### ISSUE TITLE
Still able to shoot while out of ammo or needing to reload.

### ISSUE THREAD

**Issue by Sluggies** [Servius/tfa_base_rp_friendly#4]
When I shoot it looks like this.

![image](https://cloud.githubusercontent.com/assets/27983548/25364585/4d2496f0-2918-11e7-9f06-be52ac31a146.png)

I also was wondering if it would be okay for me to rehost the mats/models from the base so that people who join aren't missing the muzzleflash textures or whatever.

![image](https://cloud.githubusercontent.com/assets/27983548/25364625/9361e8f2-2918-11e7-902f-746656158a95.png)

![image](https://cloud.githubusercontent.com/assets/27983548/25364634/9e3f0b9c-2918-11e7-88f8-96d5deaac7e0.png)

**Comment by Servius** [comment]
Setting it up via fastdl or setting up a resource.AddFile is %100 okay.
